### ISSUE TITLE
Would prefer Groovy's Elvis operator "?:" instead of "??"

### ISSUE THREAD

**Issue by HendrikJan** [gbracha/nullAwareOperators#4]
```
a ?: b
```

looks more descriptive to me than

```
a ?? b
```

to me, because it contains both characters of the more verbose syntax

```
a ? a : b;
```

**Comment by seaneagan** [comment]
The more verbose syntax is actually `a == null ? b : a` or equivalently `a != null ? a : b`.  Personally I don't see an obvious expansion of `a ?: b` to either of those.

One other syntax to consider would be `a else b`.  But `??` is more similar to `?.`.

**Comment by munificent** [comment]
If you look around, this same operator is spelled either `??` or `?:` in a bunch of different languages. I don't think either one has a big majority. C# and Swift use `??`, PHP and Groovy use `?:`.

Personally, I prefer `??`, in particular because it ties in nicely with Sean's suggestion about compound assignment in #6.
